apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: app-2048

#crate service
#command: kubectl apply -f service.yaml -n game-2048
#command: kubectl get svc -n game-2048
